sudo: required
dist: xenial
env:
  - PY=e ANGR_ROOT=~/angr-dev
install:
  - pushd "$TRAVIS_BUILD_DIR"
  - popd
  - cd ~
  - ( curl https://raw.githubusercontent.com/angr/angr-dev/$TRAVIS_BRANCH/tests/travis-install.sh | grep -v 404 || curl https://raw.githubusercontent.com/angr/angr-dev/master/tests/travis-install.sh ) | bash
  - pushd "$TRAVIS_BUILD_DIR"
  - popd
  - pwd && cd "$TRAVIS_BUILD_DIR" && make install
script: make build
deploy:
  provider: pages
  keep-history: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
