sudo: required
dist: xenial
env:
  - PY=e ANGR_ROOT=~/angr-dev
install:
  - sudo apt-get update
  - pushd ~
  - git clone -q https://github.com/angr/angr-dev
  - cd angr-dev
  - export VIRTUALENVWRAPPER_PYTHON=$(pyenv which python)
  - ./setup.sh -i -w -b "$BRANCH" -"$PY" angr -s -c -C
  - sudo apt-get install python3 python3-pip hugo
  - hugo version
  - sudo -H pip3 install --force-reinstall virtualenv virtualenvwrapper
  - popd
  - make install
script: make build
deploy:
  provider: pages
  keep-history: true
  skip-cleanup: true
  local-dir: public
  on:
    branch: master
