sudo: required
dist: xenial
env:
  - PY=e ANGR_ROOT=~/angr-dev
install:
  - sudo apt-get update
  - pushd ~
  - git clone -q https://github.com/angr/angr-dev
  - cd angr-dev
  - export VIRTUALENVWRAPPER_PYTHON=$(pyenv which python)
  - ./setup.sh -i -w -b "$BRANCH" -"$PY" angr -s -c -C
  - pip install virtualenv virtualenvwrapper
  - ls /usr/local/bin
  - which virtualenvwrapper.sh
  - popd
  - make install
script: make build
deploy:
  provider: pages
  keep-history: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
