baseURL = "https://angr.github.io/"
languageCode = "en-us"
title = "angr"
pygmentsCodeFences = true
pygmentsUseClasses = true

[[menu.main]]
  name = "home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "blog"
  url = "/blog"
  weight = 2
[[menu.main]]
  name = "docs"
  url = "http://docs.angr.io/"
  weight = 3
[[menu.main]]
  name = "code"
  url = "https://github.com/angr"
  weight = 4
[[menu.main]]
  name = "get involved!"
  url = "/#contact"
  weight = 5

[taxonomies]
  tag = "tags"
  author = "authors"

[params]
  announcement = "As of angr 8, angr will *only support Python 3.x*. For a handy guide on porting your code to Python 3 and angr 8, see [the angr 8 porting guide.](https://github.com/angr/angr-doc/blob/py3k/MIGRATION.md)."

[permalinks]
  top = "/:filename/"
