baseURL = "https://nilocunger.github.io/"
languageCode = "en-us"
title = "angr"
pygmentsCodeFences = true
pygmentsUseClasses = true

[[menu.main]]
  name = "home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "blog"
  url = "/blog"
  weight = 2
[[menu.main]]
  name = "docs"
  url = "http://docs.angr.io/"
  weight = 3
[[menu.main]]
  name = "code"
  url = "https://github.com/angr"
  weight = 4
[[menu.main]]
  name = "get involved!"
  url = "/#contact"
  weight = 5

[taxonomies]
  tag = "tags"
  author = "authors"

[params]
  announcement = "We're reviving the angr blog! For a tutorial on extending angr and much more soon, see [here](/blog)!"

[permalinks]
  top = "/:filename/"
